### ISSUE TITLE
My Overflow menu is dislocation

### ISSUE THREAD

**Issue by Rachel030219** [dandar3/android-support-v7-appcompat#1]
Why?How can I fix it?

**Comment by Rachel030219** [comment]
http://jianguoyun.com/p/DYCukl0QmIrqBRi5yw0 screenshot

**Comment by dandar3** [comment]
Can you share some of the code? theme, menu, strings, activitity? Does it behave correctly if not using CJK texts?

**Comment by Rachel030219** [comment]
It is all using Chinese...I just create menu as usual...Let me try to use English...

**Comment by Rachel030219** [comment]
I used English,but it is still wrong...

**Comment by dandar3** [comment]
I assume it worked correctly with previous appcompat version. Just confirming, when you updated to appcompat 23.0.0 of appcompat you canged your project compile target to Android API to 23. 

I wonder if it might something to do with the specific device you're running this one, maybe try it on a few emulators, with different densities and maybe screen sizes.

**Comment by Rachel030219** [comment]
I don't have a computer,so I can only use AIDE.But at Galaxy Note 3,it works success.

**Comment by Rachel030219** [comment]
In Octodroid,the menu was success. http://jianguoyun.com/p/DdVaOCMQmIrqBRj40Q0 This is screenshot.

**Comment by dandar3** [comment]
Sorry, I don't use AIDE. If it has worked correctly with previous library versions and it doesn't with latest one (23.0.1), then it sounds like a bug. You can report issues with the support library here:

https://code.google.com/p/android/issues/entry?template=Support%20Library%20bug

**Comment by Rachel030219** [comment]
Thank you anyway.I think it is best for me to try the latest library.
