### ISSUE TITLE
Conversion to Dalvik format failed with error 1

### ISSUE THREAD

**Issue by tim777z** [dandar3/android-support-v7-appcompat#4]
I keep getting Conversion to Dalvik format failed with error 1 after importing android-support-v7-appcompat from SVN url in Eclipse (Version: 2018-12 (4.10.0)) when I attempt to export an android application from my project (SquareActivity) in eclipse workspace. I'm stumped as to what to do, and realized my project is ruined now, as a result. 

![image](https://user-images.githubusercontent.com/11827348/52488731-2c1c8c00-2bc9-11e9-80b5-dbe255363a90.png)

**Comment by dandar3** [comment]
In your screenshot I can see only `android-support-v7-appcompat` being version 28.0.0. I would recommend removing all `android-support-*` and `android-arch-*` projects from your workspace, check you don't have any other support-library libs into any of your projects `\libs\` folders.

Then import `android-support-v7-appcompat` 28.0.0 and dependant libraries following the video instructions at the end of this page: https://github.com/dandar3/android-support-library-README

File > Import... > Team > Team Project Set > URL:
https://raw.githubusercontent.com/dandar3/android-support-v7-appcompat/28.0.0/.projectset

**Comment by dandar3** [comment]
No response since, closing for now, can be reopened if needed.

PS: Heads up, AndroidX Appcompat 1.x is coming soon to replace the old Android Support Library.
