### ISSUE TITLE
Need some support library for Androidx.

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-support-v7-appcompat#5]
Hello Dandar,
I need androidx.constraintlayout, adroidx.appcompat, androidx.recyclerview for implement. Can you help me with this ? Because i need to use it on GPS ads that You provide for androidx latest 18.3.0. 

Thank you.

**Comment by dandar3** [comment]
Absolutely, we now have all the scripts written and working for this. In fact an earlier version is already available, see the Import notes below.
https://github.com/dandar3/android-androidx-appcompat

Working on preparing version 1.1.0 and testing it. (Y)

**Comment by dandar3** [comment]
@vijaybhairavjibhaiaslaliya 
Please see this page on Jetpack (AndroidX) related libraries, you can create issues there to request libraries / version you need (Y)
https://github.com/dandar3/android-androidx-README

**Comment by vijaybhairavjibhaiaslaliya** [comment]
thanks for your support

**Comment by vijaybhairavjibhaiaslaliya** [comment]
thanks

**Comment by dandar3** [comment]
(Y) Please let me know if there's another library you need or if you're having any problems. Good luck!
